version: "3.7"
services:
  snakemake:
    build: .
    container_name: deepvariant
    volumes:
      - ${PWD}/working:/home/deepvariant/working
    working_dir: /home/deepvariant/working
    tty: true
    command: /bin/bash
    cap_drop:
      - CAP_NET_RAW
    security_opt:
      - no-new-privileges